#!/bin/sh
# Automatically adds branch name and branch description to every commit message.

NAME=$(git branch | grep '*' | sed 's/* //')
DESCRIPTION=$(git config branch."$NAME".description)
PREV_EDIT="$(cat "$1")"


if [[ "$PREV_EDIT" == *"$NAME"* ]]; then
  echo "$(cat "$1")" > "$1"
else
  echo "$NAME"': '"$(cat "$1")" > "$1"

  if [ -n "$DESCRIPTION" ]
  then
    echo "" >> "$1"
    echo $DESCRIPTION >> "$1"
  fi
fi
